name: Update Blog - Projects

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-blog:
    name: Update README with latest posts
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPOSITORY: ${{ secrets.GH_REPOSITORY }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
    - run: node update.js
    - run: node update-projects.js

